In [0]:
import numpy as np

In [0]:

np.random.seed(666)

In [0]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [0]:
x_train.shape, y_train.shape
miniX, miniy= x_train[:200] ,y_train[:200]

In [0]:
def feed_forw( x , weigths_layers ,activation ='relu'):
#   input_layer = x+layers_bayes[0]
  for i, w in enumerate(weigths_layers):
    
    # maybe ravel and hstack? 
    x_andb = np.hstack ((x.ravel(), np.array([1]))) 
    x_andb=x_andb.reshape(-1,1)
    weigthed_x = x_andb@w.reshape(1,-1)
#     print(weigthed_x.shape)
#     print(w.shape)
    # suming inputs:
    sigma_x = np.sum (weigthed_x, axis = 0)
#     print (sigma_x.shape) 
    if i<len(weigths_layers)-1:
      if activation == 'relu':
        x = np.maximum(sigma_x , np.zeros(len(sigma_x)))  # relu for each indices 
#         print( x.shape)
    else:
      x= 1/( 1+ np.exp(sigma_x ))   # else or for output - logistic function 
      if i == len(weigths_layers)-1:
        break     
  return  x    


def predict (X):
  y= []
  for x in X:
    y = argmax(feed_forw(x))  # we return the most probabal as label 
  return y



def fit (X,y, lr = 1):
  #inetelizing neural net
  # change it laer to somthing mor general -> easier way to chang hien layers shapes

  input_len= x_train[0].shape
  hidden_len=3
  hidden_len2=2
  weigths_layers = [np.random.rand(*input_len) , np.random.rand(hidden_len) , np.random.rand(hidden_len2), np.random.rand(10)]
#   weigths_layers= [ np.random.rand(*x_train[0].shape)  for i in  layers_bayes[1:] for j in i]

  for i,x in  enumerate(X):
    labels_prob = feed_forw(x, weigths_layers)
    
    true_p = np.zeros(10)
    true_p[ y[i]]=1
    weigths_layers= backprop(true_p , labels_prob , x,weigths_layers ,lr)
    
    
    
    
    
def backprop( y,y_hat, x ,weigths_layer,  lr=1 , activation ='relu'):
#   a= y_hat
  weigths_layer =weigths_layer[::-1]
  layers = len(weigths_layer)
  
  
  
  for i in range( layers ):
    
    
    x= x.ravel()
    w= weigths_layer[i]
#     w= w.ravel()
    if (i==0) or (activation!='relu' ):
      w+= (1/len(y) )* lr * ( (y-y_hat)*(1/(1+np.exp(y_hat)) ) @ (1-1/(1+np.exp(y_hat))) ) # fix derrivate by chain role
#        w+= (1/len(y) )* lr * x@ ( (y-y_hat)@(1/(1+np.exp(y_hat)) ) @ (1-1/(1+np.exp(y_hat))) )
    else:  
#       w+= lr* x@w.reshape(1,-1)  # updating for hidden/input  relu  .. maybe change to y_hat
      print(y_hat.reshape(-1,1).shape ,w.reshape(1,-1).shape ,w.shape , y_hat.shape)
      w+= (lr* np.sum(y_hat.reshape(-1,1) @ w.reshape(1,-1) ,axis =0)).reshape(*w.shape)
    weigths_layer[i] =w
  return   weigths_layer
#         np.sum(h.reshape(-1,1)@w.reshape(1,-1) ,axis =0)# updating for hidden/input  relu  .. maybe change to y_hat
  
  
   
y = fit( miniX, miniy )
    
  

(10, 1) (1, 2) (2,) (10,)
(10, 1) (1, 3) (3,) (10,)
(10, 1) (1, 784) (28, 28) (10,)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:19: RuntimeWarning: overflow encountered in exp


ValueError: ignored

In [0]:
#inetelizing neural net

input_len= x_train[0].shape
hidden_len=3
hidden_len2=2

layers_bayes = [np.random.rand(*input_len) , np.random.rand(hidden_len) , np.random.rand(hidden_len2), np.random.rand(1)]

weigths_layers= [ np.random.rand(*x_train[0].shape)  for i in  layers_bayes[1:] for j in i]



# change out to 10?

In [0]:
# # pred :
# def pred (x,w,b,activation):
#   y_pred = x@w +b
#   if activation == 'relu':
#     return max(0, y_pred)
#   if activation == 'sig':
#     return 1/(1+2.21^y_pred)
  
  
  
# def error(y_hat, y_real):
#     return 0.5 * (y_hat - y_real)**2

# def delta (y_hat, y_real):
#     return y_hat - y_real

# def backprop(x, y, w, b, lr , activation):
  
  
#     y_hat = pred(x, w, b , activation)

#     # Layer Error
#     e_o = error(y_hat, y_real)  
# #     e_h = e_o  

#     # Cost derivative for weights
#     d_b =  e_o * 
#     d_w =  e_o * x

#     # Update weights
#     b -= lr * b
#     w -= lr * w
#     return( b, w)
  
  
  
    
    

  


SyntaxError: ignored

SyntaxError: ignored

In [0]:
layers_bayes

[array([0.88187757]),
 array([0.08994311, 0.00569416, 0.50994517]),
 array([0.04504762, 0.09009201]),
 array([0.25051206])]

In [0]:
c= np.hstack ((miniX[0].ravel(), np.array([1]))) 
w=np.array([3,2,1])

c=c.reshape(-1,1)

In [0]:
w.shape
c.shape
c@w.reshape(1,-1)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       ...,
       [0., 0., 0.],
       [0., 0., 0.],
       [3., 2., 1.]])

In [0]:
(1/len(y) ) ,
,lr , x, 
( (y-y_hat),
 (1/(1+np.exp(y_hat)) ) 
 ,
 (1-1/(1+exp(y_hat))) )

NameError: ignored

In [0]:
# (1/len(y) )* lr * x@ ( (y-y_hat)@ (1/(1+np.exp(y_hat)) ) @ (1-1/(1+np.exp(y_hat))) )

w=np.random.rand(10) 
y=np.random.rand(10) 
y_hat=np.random.rand(10)
x=np.random.rand(784)

In [0]:
s = 1-1/(1+np.exp(y_hat))

In [0]:
s2 =1/(1+np.exp(y_hat))
drr =s@s2

In [0]:
a=y-y_hat
a*drr


array([-0.31589264, -1.21053469,  0.4064461 ,  0.05560384,  0.34548348,
        0.28590581,  0.73674488,  1.63257562,  1.25857438,  0.78139816])

In [0]:
(y-y_hat)@ (1/(1+np.exp(y_hat)) ) @ (1-1/(1+np.exp(y_hat)))

ValueError: ignored

In [0]:
w = np.random.rand(2)

h = np.random.rand(10)

np.sum(h.reshape(-1,1)@w.reshape(1,-1) ,axis =0)

array([1.35249767, 0.32463245])

In [0]:
np.dot(h,w)

ValueError: ignored